name: Commit Tasks
description: Only runs on specific files and branches.

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"

permissions:
  contents: write

concurrency:
  group: on-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/spotless.yml

  build:
    name: Build Mod
    uses: ./.github/workflows/build.yml
