name: Run Tasks on PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/spotless.yml

  build:
    name: Build Mod
    uses: ./.github/workflows/build.yml
