name: PR Tasks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/spotless.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build the Mod
        uses: ./.github/actions/build_mod
