name: PR Tasks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check:
    name: Run Checks
    uses: ./.github/workflows/spotless.yml

  build:
    name: Build Mod
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build_mod
